const SET_PLAYLIST_ID: string = 'SET_PLAYLIST_ID';
const SET_PLAYLIST_RESULTS: string = 'SET_PLAYLIST_RESULTS';
const SET_OUTPUT_PLAYLIST_NAME: string = 'SET_OUTPUT_PLAYLIST_NAME';

export { SET_PLAYLIST_ID, SET_PLAYLIST_RESULTS, SET_OUTPUT_PLAYLIST_NAME };
