const SET_PLAYLIST_ID: string = "SET_PLAYLIST_ID";
const SET_PLAYLIST_RESULTS: string = "SET_PLAYLIST_RESULTS";
const SET_OUTPUT_PLAYLIST_NAME: string = "SET_OUTPUT_PLAYLIST_NAME";
const SET_INPUT_FORM_ERROR: string = "SET_INPUT_FORM_ERROR";
const SET_OUPUT_FORM_ERROR: string = "SET_OUPUT_FORM_ERROR";

export {
  SET_PLAYLIST_ID,
  SET_PLAYLIST_RESULTS,
  SET_OUTPUT_PLAYLIST_NAME,
  SET_INPUT_FORM_ERROR,
  SET_OUPUT_FORM_ERROR,
};
